services:
  mysql:
    image: mysql
    container_name: mysql-server-dev
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: yanit_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: [ "redis-server", "--timeout", "600", "--tcp-keepalive", "300" ]
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
