services:
  user-service:
    build:
      context: userService
      dockerfile: Dockerfile
    container_name: user-service
    working_dir: /app
    volumes:
      - ./userService:/app
    ports:
      - "4243:4243"
    env_file:
      - ./userService/.env
    restart: always
    command: ["pm2-runtime", "index.js"]

  mail-service:
    build:
      context: mailService
      dockerfile: Dockerfile
    container_name: mail-service
    working_dir: /app
    volumes:
      - ./mailService:/app
    ports:
      - "4244:4244"
    env_file:
      - ./mailService/.env
    restart: always